cc_library(
    name = "utils",
    srcs = ["utils.cpp"],
    hdrs = ["utils.h"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tcp_sock_stat",
    srcs = ["tcp_sock_stat.cpp"],
    hdrs = [],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)