cc_library(
    name = "utils",
    srcs = ["utils.cpp"],
    hdrs = ["utils.h"],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "tcp_stat_manager",
    srcs = ["tcp_stat_manager.cpp"],
    hdrs = [
        "tcp_stat_manager.h",
    ],
    deps = [
        "@com_github_google_glog//:glog",
    ],
    visibility = ["//visibility:public"],
)