replica:
  ips: 
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  - "127.0.0.5"
  - "127.0.0.6"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 3000
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 150
  port: 7019
  delayLowerBound: 1
  delayUpperBound: 25
  useSimulatedLinks: false
  linkLossRate: 0.01
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 25
  safetyMarginStepSize: 5
  workerThreadsCount: 12
  fdMode: raft
  clientPort: 10032
  internalBasePort: 8220