replica:
  ips: 
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  - "127.0.0.5"
  - "127.0.0.6"
  runtimeSeconds: 300
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 30
  port: 7859
  delayLowerBound: 10
  delayUpperBound: 250
  useSimulatedLinks: false
  linkLossRate: 0.1
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.95
  heartbeatIntervalMargin: 85