replica:
  ips: 
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  - "127.0.0.5"
  - "127.0.0.6"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 300
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: true
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 150
  port: 7127
  delayLowerBound: 1
  delayUpperBound: 25
  # if use simulated links is true, there is a chance that the proposal to followers will not be sent. 
  # this is used to verify correctness of the implementation. 
  useSimulatedLinks: false
  linkLossRate: 0.01
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  heartbeatIntervalMargin: 85
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 25
  safetyMarginStepSize: 5