replica:
  ips: 
  - "127.0.0.2"
  - "127.0.0.3"
  - "127.0.0.4"
  - "127.0.0.5"
  - "127.0.0.6"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 600
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 350
  port: 7019
  delayLowerBound: 1
  delayUpperBound: 25
  useSimulatedLinks: false
  linkLossRate: 0.01
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 25
  safetyMarginStepSize: 5
  workerThreadsCount: 11
  fdMode: raft
  clientPort: 10991
  internalBasePort: 8591
  eligibleLeaders: [0]
  checkOverhead: false
  senderThreadsCount: 8
  spinCheckCount: 4
  spinCheckInterval: 18
  # how many times per second polls and send netlink sockets data
  tcpMonitorFrequency: 100
