replica:
  ips: 
  - "10.0.0.2"
  - "10.0.0.3"
  - "10.0.4.2"
  - "10.0.1.2"
  - "10.0.1.3"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 600
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: true
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 150
  port: 6555
  delayLowerBound: 1
  delayUpperBound: 25
  useSimulatedLinks: false
  linkLossRate: 0
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 25
  safetyMarginStepSize: 5
  workerThreadsCount: 4
  fd_mode: raft
