replica:
  ips: 
  - "10.10.4.2"
  - "10.10.1.2"
  - "10.10.2.2"
  - "10.10.3.2"
  - "10.10.5.2"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 300
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 150
  port: 7912
  delayLowerBound: 10
  delayUpperBound: 250
  useSimulatedLinks: false
  linkLossRate: 0
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  heartbeatIntervalMargin: 75