replica:
  ips: 
  - "10.0.0.2"
  - "10.0.0.3"
  - "10.0.4.2"
  - "10.0.1.2"
  - "10.0.1.3"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 3000
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 100
  port: 7912
  delayLowerBound: 10
  delayUpperBound: 250
  useSimulatedLinks: false
  linkLossRate: 0
  checkFalsePositiveRate: true
  tcp_monitor: false
  confidenceLevel: 0.999
  heartbeatIntervalMargin: 85
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 25
  safetyMarginStepSize: 5