replica:
  ips: 
  - "10.0.0.2"
  - "10.0.0.3"
  - "10.0.4.2"
  - "10.0.1.2"
  - "10.0.1.3"
  interfaces:
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  - "eth1"
  runtimeSeconds: 300
  timeoutLowerBound: 150
  timeoutUpperBound: 300
  failureLeader: false
  # if the failureLeader is true, after maxHeartbeats number of heartbeats, the leader will fail
  maxHeartbeats: 1000
  port: 6119
  delayLowerBound: 1 
  delayUpperBound: 25
  useSimulatedLinks: false
  linkLossRate: 0
  checkFalsePositiveRate: true
  tcp_monitor: true
  confidenceLevel: 0.999
  testPetition: false
  heartbeatIntervalMargin: 75
  safetyMarginLowerBound: 45
  safetyMarginStepSize: 2
  workerThreadsCount: 11
  fdMode: Jacobson
  clientPort: 10083
  internalBasePort: 8230
  eligibleLeaders: [0, 1, 2, 3, 4]
  checkOverhead: false
  senderThreadsCount: 8
  spinCheckCount: 4
  spinCheckInterval: 18
  tcpMonitorFrequency: 10
